# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-26 19:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlliesOrganizations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='AttributesSavingThrowsMixin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strength', models.IntegerField(default=0)),
                ('dexterity', models.IntegerField(default=0)),
                ('constitution', models.IntegerField(default=0)),
                ('intelligence', models.IntegerField(default=0)),
                ('wisdom', models.IntegerField(default=0)),
                ('charisma', models.IntegerField(default=0)),
                ('strength_prof', models.BooleanField(default=False)),
                ('dexterity_prof', models.BooleanField(default=False)),
                ('constitution_prof', models.BooleanField(default=False)),
                ('intelligence_prof', models.BooleanField(default=False)),
                ('wisdom_prof', models.BooleanField(default=False)),
                ('charisma_prof', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='BasicFactsMixin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_name', models.CharField(max_length=50, null=True)),
                ('character_class', models.CharField(max_length=50, null=True)),
                ('character_level', models.IntegerField(default=1)),
                ('character_race', models.CharField(max_length=50, null=True)),
                ('character_background', models.CharField(max_length=50, null=True)),
                ('character_alignment', models.CharField(max_length=50, null=True)),
                ('character_exp_points', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=30)),
                ('facts', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='facts', to='character_sheets.BasicFactsMixin')),
            ],
        ),
        migrations.CreateModel(
            name='CharacterLooksBackstoryMixin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('eyes', models.CharField(max_length=10)),
                ('skin', models.CharField(max_length=10)),
                ('hair', models.CharField(max_length=10)),
                ('appearance', models.CharField(max_length=500)),
                ('character_backstory', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentMixin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='HitDiceMixin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_hit_die', models.CharField(choices=[('D10', 'd10'), ('D8', 'd8'), ('D6', 'd6')], max_length=4)),
                ('primary_class_level', models.IntegerField()),
                ('multiclass_hit_die', models.CharField(choices=[('D10', 'd10'), ('D8', 'd8'), ('D6', 'd6')], max_length=4)),
                ('multiclass_level', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LanguageMixin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('dungeon_master', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerDescriptionMixin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_type', models.CharField(choices=[('PERSONALITY_TRAITS', 'Personality Traits'), ('IDEALS', 'Ideals'), ('FLAWS', 'Flaws'), ('BONDS', 'Bonds'), ('FEATURES_AND_TRAITS', 'Features and Traits'), ('GENERIC_DESCRIPTION', 'Generic Description')], max_length=20)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SkillsMixin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acrobatics', models.IntegerField(default=0)),
                ('animal_handling', models.IntegerField(default=0)),
                ('arcana', models.IntegerField(default=0)),
                ('athletics', models.IntegerField(default=0)),
                ('deception', models.IntegerField(default=0)),
                ('history', models.IntegerField(default=0)),
                ('insight', models.IntegerField(default=0)),
                ('intimidation', models.IntegerField(default=0)),
                ('investigation', models.IntegerField(default=0)),
                ('medicine', models.IntegerField(default=0)),
                ('nature', models.IntegerField(default=0)),
                ('perception', models.IntegerField(default=0)),
                ('performance', models.IntegerField(default=0)),
                ('persuasion', models.IntegerField(default=0)),
                ('religion', models.IntegerField(default=0)),
                ('sleight_of_hand', models.IntegerField(default=0)),
                ('stealth', models.IntegerField(default=0)),
                ('survival', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=100)),
                ('spell_level', models.IntegerField(default=0)),
                ('casting_time', models.IntegerField(default=0)),
                ('range', models.IntegerField(default=0)),
                ('shape', models.CharField(choices=[('TCH', 'Touch'), ('CN', 'Cone'), ('CB', 'Cube')], max_length=20)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SpellsMixin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spellcasting_class', models.CharField(choices=[('INT', 'Intelligence'), ('CHA', 'Charisma'), ('WIS', 'Wisdom'), ('CON', 'Constitution')], max_length=20)),
                ('spellcasting_ability', models.IntegerField()),
                ('spell_save_dc', models.IntegerField()),
                ('spell_attack_bonus', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WeaponsMixin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('attack_bonus', models.IntegerField()),
                ('damage_type', models.CharField(max_length=20)),
                ('hit_die', models.CharField(choices=[('D10', 'd10'), ('D8', 'd8'), ('D6', 'd6')], max_length=4)),
                ('description', models.CharField(max_length=200)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='languagemixin',
            name='races_used_by',
            field=models.ManyToManyField(to='character_sheets.Race'),
        ),
    ]
