# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-26 19:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('character_sheets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='name',
        ),
    ]
