# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-07-26 19:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('character_sheets', '0002_remove_character_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='facts',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='facts', to='character_sheets.BasicFactsMixin'),
        ),
    ]
